name: 🏏 KBO 데이터 일일 자동 업데이트

on:
  schedule:
    # 매일 한국시간 오후 6시 (UTC 09:00)
    - cron: '0 9 * * *'
    # 매일 한국시간 오후 10시 (UTC 13:00) 
    - cron: '0 13 * * *'
    # 매일 한국시간 자정 12시 (UTC 15:00)
    - cron: '0 15 * * *'
  
  # 수동 실행 가능
  workflow_dispatch:

jobs:
  update-kbo-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 저장소 체크아웃
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 🟢 Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 의존성 설치
      run: |
        npm ci
        # Puppeteer 의존성 설치
        npx puppeteer browsers install chrome
        
    - name: 🤖 KBO 데이터 크롤링 및 업데이트
      run: |
        echo "🏏 KBO 데이터 업데이트 시작..."
        echo "📅 실행 시간: $(date)"
        
        # 완전 자동화 시스템 실행 (순위 + 경기결과 + 상대전적 + 웹사이트 업데이트)
        node complete-kbo-automation.js
        
        echo "✅ 데이터 업데이트 완료"
        
    - name: 📊 변경사항 확인
      id: changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "변경사항이 있습니다."
          echo "has_changes=true" >> $GITHUB_OUTPUT
          git status
        else
          echo "변경사항이 없습니다."
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
        
    - name: 🚀 변경사항 커밋 및 푸시
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add .
        
        git commit -m "🚀 KBO 완전 자동화 업데이트 - $(date '+%Y-%m-%d %H:%M:%S')

        ✅ 완전 통합 자동화 시스템:
        - 📊 KBO 공식 팀 순위/통계 (최근10경기, 연속기록)
        - ⚾ 네이버 스포츠 최신 경기 결과 크롤링
        - 🔄 상대전적 실시간 자동 업데이트  
        - 🌐 웹사이트 데이터 완전 동기화
        - 🎯 매직넘버 실시간 재계산

        🤖 Generated with GitHub Actions (Complete Automation)
        🔗 Workflow: ${{ github.workflow }}
        📅 Run: ${{ github.run_number }}"
        
        git push
        
    - name: 📢 결과 요약
      run: |
        echo "🎉 KBO 데이터 업데이트 작업 완료!"
        echo "📅 실행 시간: $(date)"
        echo "🔗 워크플로우: ${{ github.workflow }}"
        echo "📊 실행 번호: ${{ github.run_number }}"
        
        if [[ "${{ steps.changes.outputs.has_changes }}" == "true" ]]; then
          echo "✅ 새로운 데이터가 업데이트되었습니다."
        else
          echo "📌 변경사항이 없어 업데이트하지 않았습니다."
        fi