name: KBO 자동 데이터 크롤링 및 업데이트

on:
  # 하루 3번 한국시간 기준 실행
  schedule:
    # 오후 6시 (UTC 09:00)
    - cron: '0 9 * * *'
    # 오후 10시 (UTC 13:00)  
    - cron: '0 13 * * *'
    # 밤 12시 (UTC 15:00)
    - cron: '0 15 * * *'
  
  # 수동 실행 가능
  workflow_dispatch:
    inputs:
      target_date:
        description: '크롤링할 날짜 (YYYY-MM-DD, 비어있으면 현재 월)'
        required: false
        type: string

jobs:
  crawl-and-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Python 환경 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Node.js 환경 설정  
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Chrome 설치
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: ChromeDriver 설치
      uses: nanasess/setup-chromedriver@master
    
    - name: Python 패키지 설치
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Node.js 의존성 설치
      run: npm install
    
    - name: KBO 데이터 크롤링 실행
      run: |
        echo "🚀 KBO 데이터 크롤링 시작..."
        
        # 현재 년월 계산 (한국시간 기준)
        CURRENT_YEAR=$(TZ='Asia/Seoul' date +%Y)
        CURRENT_MONTH=$(TZ='Asia/Seoul' date +%m)
        
        echo "📅 크롤링 대상: ${CURRENT_YEAR}년 ${CURRENT_MONTH}월"
        
        # Python 크롤러 실행 (headless 모드)
        python kbo-python-working-crawler.py
        
        # data 폴더 확인 및 생성
        mkdir -p data
        
        # 크롤링 결과 확인 (이제 clean.txt 파일에 직접 추가됨)
        echo "📁 크롤링 완료 - data/${CURRENT_YEAR}-season-data-clean.txt 업데이트됨"
    
    - name: Node.js 데이터 처리 실행
      run: |
        echo "🔄 Node.js 데이터 처리 시작..."
        
        # 현재 연도 계산
        CURRENT_YEAR=$(TZ='Asia/Seoul' date +%Y)
        
        # clean.txt 파일을 Node.js로 처리
        if [ -f "data/${CURRENT_YEAR}-season-data-clean.txt" ]; then
          # process-season-data.js가 clean.txt 파일을 읽도록 설정되어 있음
          node scripts/process-season-data.js
          echo "✅ 데이터 처리 완료"
        else
          echo "⚠️ 처리할 시즌 데이터가 없습니다: data/${CURRENT_YEAR}-season-data-clean.txt"
          exit 0
        fi
    
    - name: 변경사항 확인 및 커밋
      run: |
        echo "📝 변경사항 확인 중..."
        
        # Git 설정
        git config --local user.email "action@github.com"
        git config --local user.name "KBO Auto Crawler"
        
        # 변경된 파일들 확인
        git add -A
        
        if git diff --staged --quiet; then
          echo "📭 변경사항이 없습니다"
          exit 0
        fi
        
        # 커밋 메시지 생성
        CURRENT_DATE=$(TZ='Asia/Seoul' date +"%Y-%m-%d %H:%M")
        CURRENT_TIME=$(TZ='Asia/Seoul' date +"%H:%M")
        
        # 실행 시간에 따른 메시지 설정
        if [[ "$CURRENT_TIME" < "19:00" ]]; then
          TIME_MSG="🌅 오후 6시 경기 결과 업데이트"
        elif [[ "$CURRENT_TIME" < "23:00" ]]; then
          TIME_MSG="🌆 오후 10시 경기 결과 업데이트"
        else
          TIME_MSG="🌙 밤 12시 최종 경기 결과 업데이트"
        fi
        
        COMMIT_MESSAGE="🤖 KBO 데이터 자동 업데이트 - ${CURRENT_DATE}
        
        ${TIME_MSG}
        🎯 자동 크롤링 및 데이터 처리 완료
        📊 웹서비스 데이터 파일 업데이트
        
        🤖 Generated with GitHub Actions
        Co-Authored-By: KBO-Auto-Crawler <action@github.com>"
        
        # 변경사항 커밋
        git commit -m "$COMMIT_MESSAGE"
        
        echo "✅ 커밋 완료: $COMMIT_MESSAGE"
    
    - name: 변경사항 푸시
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    
    - name: 크롤링 결과 요약
      run: |
        echo "🎉 KBO 자동 크롤링 완료!"
        echo "📊 업데이트된 파일들:"
        echo "   - magic-number/kbo-rankings.json (순위 데이터)"
        echo "   - magic-number/kbo-records.json (상대전적 데이터)"  
        echo "   - output/service-data.json (통합 서비스 데이터)"
        echo "📅 다음 실행 스케줄:"
        echo "   - 🌅 오후 6시 (한국시간)"
        echo "   - 🌆 오후 10시 (한국시간)"
        echo "   - 🌙 밤 12시 (한국시간)"
    
    - name: 실패 시 알림 (선택사항)
      if: failure()
      run: |
        echo "❌ KBO 자동 크롤링 실패"
        echo "🔍 로그를 확인하여 문제를 해결해주세요"
        # 여기에 Slack, Discord 등 알림 연동 가능