name: Pages Deploy on Bot Push

on:
  push:
    branches: [ main ]
    # 봇에 의한 커밋일 때만 실행
    # 커밋 메시지에 "🤖 KBO 데이터 자동 업데이트" 또는 "KBO Auto Crawler"가 포함된 경우

# 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 실행 방지
concurrency:
  group: pages-deploy-bot
  cancel-in-progress: true

jobs:
  deploy:
    # 봇 커밋인지 확인 후 실행
    if: contains(github.event.head_commit.message, '🤖 KBO 데이터 자동 업데이트') || contains(github.event.head_commit.message, 'KBO Auto Crawler')
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: 📁 저장소 체크아웃
      uses: actions/checkout@v4

    - name: 📁 배포 전용 디렉토리 생성
      run: |
        echo "📁 배포 전용 디렉토리 생성 중..."
        mkdir -p _site
        
        # 필요한 파일들만 복사
        cp index.html _site/
        cp -r magic-number/ _site/
        cp -r images/ _site/ 2>/dev/null || true
        cp *.json _site/ 2>/dev/null || true
        cp manifest.json _site/ 2>/dev/null || true
        cp robots.txt _site/ 2>/dev/null || true
        cp sitemap.xml _site/ 2>/dev/null || true
        cp ads.txt _site/ 2>/dev/null || true
        cp CNAME _site/ 2>/dev/null || true
        
        # 배포 디렉토리 크기 확인
        DEPLOY_SIZE=$(du -sh _site | cut -f1)
        echo "📊 배포 디렉토리 크기: ${DEPLOY_SIZE}"
        
        echo "✅ 배포 전용 디렉토리 생성 완료"

    - name: 📦 Pages 아티팩트 업로드
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'
        
    - name: 🌐 GitHub Pages 배포
      id: deployment
      uses: actions/deploy-pages@v4
      timeout-minutes: 10
        
    - name: ✅ 배포 완료 확인
      run: |
        echo "🚀 GitHub Pages 배포 완료!"
        echo "🌐 배포 URL: ${{ steps.deployment.outputs.page_url }}"
        echo "📊 봇 푸시에 의한 자동 배포 성공"