name: Update KBO Data Daily

on:
  schedule:
    # 매일 KST 23:30 (UTC 14:30)에 실행
    - cron: '30 14 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install puppeteer cheerio axios
        
    - name: Crawl KBO data and update
      run: |
        echo "🚀 KBO 데이터 크롤링 및 업데이트 시작..."
        node scripts/simple-update.js
        echo "✅ 데이터 업데이트 완료"
      
    - name: Check for changes
      id: changes
      run: |
        git diff --quiet && echo "changed=false" >> $GITHUB_OUTPUT || echo "changed=true" >> $GITHUB_OUTPUT
        
    - name: Commit and push changes
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "noreply@github.com"
        git config --local user.name "GitHub Actions"
        
        # 현재 날짜 (KST)
        DATE=$(TZ='Asia/Seoul' date +'%Y년 %m월 %d일')
        
        git add .
        git commit -m "📊 KBO 데이터 자동 업데이트 ($DATE)

        - 순위표 및 팀 기록 업데이트
        - 매직넘버 재계산 
        - 플레이오프 진출 조건 업데이트

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: Claude <noreply@anthropic.com>"
        
        git push
        
    - name: Summary
      run: |
        if [ "${{ steps.changes.outputs.changed }}" == "true" ]; then
          echo "✅ 데이터가 성공적으로 업데이트되어 푸시되었습니다."
        else
          echo "ℹ️ 변경사항이 없어 푸시하지 않았습니다."
        fi