
name: KBO 데이터 자동 업데이트

on:
  schedule:
    # 매일 오후 6시 (KST) = UTC 09:00
    - cron: '0 9 * * *'
    # 매일 오후 10시 (KST) = UTC 13:00  
    - cron: '0 13 * * *'
    # 매일 밤 12시 (KST) = UTC 15:00
    - cron: '0 15 * * *'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-kbo-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: 의존성 설치
      run: |
        npm ci
        
    - name: KBO 데이터 전체 업데이트
      run: |
        echo "🚀 KBO 데이터 크롤링 및 업데이트 시작..."
        npm run update-data
        echo "✅ 데이터 업데이트 완료"
      
    - name: 변경사항 확인
      id: changes
      run: |
        git diff --quiet && echo "changed=false" >> $GITHUB_OUTPUT || echo "changed=true" >> $GITHUB_OUTPUT
        
    - name: 변경사항 커밋 및 푸시
      if: steps.changes.outputs.changed == 'true'
      run: |
        git config --local user.email "noreply@github.com"
        git config --local user.name "GitHub Actions"
        
        # 현재 날짜 (KST)
        DATE=$(TZ='Asia/Seoul' date +'%Y년 %m월 %d일 %H시')
        
        git add .
        git commit -m "📊 KBO 데이터 자동 업데이트 ($DATE)

        - 순위표 및 팀 기록 업데이트
        - 매직넘버 재계산 
        - 플레이오프 진출 조건 업데이트
        - HTML 파일 자동 업데이트

        🤖 자동 업데이트"
        
        git push
        
    - name: 업데이트 결과 요약
      run: |
        if [ "${{ steps.changes.outputs.changed }}" == "true" ]; then
          echo "✅ 데이터가 성공적으로 업데이트되어 푸시되었습니다."
          echo "📊 업데이트 시간: $(date)"
        else
          echo "ℹ️ 변경사항이 없어 푸시하지 않았습니다."
        fi
